[mypy]
python_version = 3.11
files = sheetkit
exclude = ^(examples|experiments)/

warn_return_any = True
warn_unused_configs = True
check_untyped_defs = True
ignore_missing_imports = True
no_implicit_optional = True

