#[tool.ruff]
# Only check files in these directories
#include = ["src/**/*.py", "tests/**/*.py"]
include = ["sheetkit/*.py", "tests/*.py", "scripts/*.py", "examples/*.py"]
# Optionally, exclude other directories just in case
#exclude = ["legacy_code", "scripts"]